<div class="jumbotron">
    <h1>Рыжов за кадром</h1>
    <p>Продукт свободного творчества на основе фреймворка Zend FW 2. Возлагаемые надежды: получить в итоге систему управления контентом для программиста.
       Система <strong>не</strong> будем иметь характеристики: понятная каждому, любой может сделать сайт, не нужно больших знаний.
       Это набор модулей-надстроек над хорошим фреймфорком.
    </p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/andydune/rznw.ru" target="_blank">Этот продукт на Гитхабе &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Контакты</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li>Имя: Андрей</li>
                    <li>Телефон: +7 (4912) 51-10-23</li>
                    <li>Еще телефон: +7 (930) 783-10-23</li>
                    <li>Skype: rzn1rzn</li>
                    <li>Электроадрес: info@rznw.ru</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Вид спереди</h3>
            </div>
            <div class="panel-body">
                <img alt="Лицо" src="/data/images/i_300.jpg" width="100%" />
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Любимое блюдо</h3>
            </div>
            <div class="panel-body">
                <img alt="Пельмени" src="/data/images/pelmeni.jpg" width="100%" />
            </div>
        </div>
    </div>
</div>
